### ISSUE TITLE
org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to <null> failed

### ISSUE THREAD

**Issue by a252937166** [foxiswho/docker-rocketmq#1]
```
docker run --name rmqconsole --link rmqserver:namesrv -e "JAVA_OPTS=-Drocketmq.namesrv.addr=IP地址:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false" -p 8180:8080 -t styletang/rocketmq-console-ng

```

IP地址我使用127.0.0.1不行，会报错，改成192开头的地址才可以，这是怎么回事呢

**Comment by foxiswho** [comment]
docker容器 是一个容器（可以看成一个服务器), 
doccker容器 与 宿主机 可以看成是两个独立的服务器
在 docker 容器内访问 127.0.0.1或localhost都是访问的这个docker容器，如果要访问宿主机必须使用宿主机IP

**Comment by a252937166** [comment]
@foxiswho 容器中的9876端口已经映射到了服务器的9876端口，我意思是在容器在使用127.0.0.1:9876和使用192.x.x.x:9876这个内网地址，应该都会访问到容器中的9876吧，但是启动console容器的时候，namesrv.addr用127.0.0.1却不行，使用内网地址才可以

**Comment by a252937166** [comment]
看了你server的port配置，就是把本机的9876指定到容器的9876吧，我想的是无论是以本机127.0.0.1或者是内网地址192或者外网地址ip的形式加9876都会访问到本机的9876，然后映射到容器里的9876啊。就是想不通唯独127.0.0.1不行，提示connet null。也只有在你这个镜像遇到了这种情况

**Comment by SnailDev** [comment]
https://blog.csdn.net/qq_40808344/article/details/88601085  @a252937166

**Comment by a252937166** [comment]
@SnailDev 我是服务器上使用127.0.0.1，应该没有什么虚拟机的说法
