### ISSUE TITLE
rmqbroker 不能启动，看不见错误日志

### ISSUE THREAD

**Issue by kanyways** [foxiswho/docker-rocketmq#10]
![image](https://user-images.githubusercontent.com/9895669/75205731-82964180-57af-11ea-84d6-aeff04192d17.png)

使用环境
- CentOS：7 x64
- Docker：19.03.6
- Docker-Compose：1.25.4

![image](https://user-images.githubusercontent.com/9895669/75205812-b5403a00-57af-11ea-92d5-4c3d3fced544.png)

**Comment by foxiswho** [comment]
你得情况应该是 日志目录 没有  写入和读取权限导致的

命令行进入  rmq 目录，执行

```shell
docker-compose down

#这里的意思是   停止删除 当前容器
```

最后执行
```shell
chmod +x  start.sh

./start.sh

# 这里意思是    重新生成容器
```
