### ISSUE TITLE
无论怎么设置brokerIP1，Mac下测试都不通过

### ISSUE THREAD

**Issue by zealinux** [foxiswho/docker-rocketmq#15]
出错信息如下：

```
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to host.docker.internal:10911 failed
```

 - broker.conf
> 无论设置成局域网IP还是`host.docker.internal`，都不行
```bash
# brokerIP1=192.168.1.2
# brokerIP1=192.168.65.2
brokerIP1=host.docker.internal
```

- docker-compose.yml 有两处修改
> 就了参数："-n","docker.for.mac.host.internal:9876"

```
# rmqnamesrv
command: ["sh","mqnamesrv", "-n", "docker.for.mac.host.internal:9876"]

# rmqbroker
command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","docker.for.mac.host.internal:9876","autoCreateTopicEnable=true"]
```

我的测试代码：
```bash
export NAMESRV_ADDR=0.0.0.0:9876
cd rocketmq-all-4.7.0-bin-release/
sh bin/tools.sh org.apache.rocketmq.example.quickstart.Producer
```

我的应用服务不会和RocketMQ在统一网络`rmq`下，也可能就不是容器启动。
测试的机器是Mac，局域网内192.168.1.2，所以没有公网IP。

**Comment by SpectatorNan** [comment]
同样的问题 有找到解决方案吗

**Comment by foxiswho** [comment]
是IP ，不是域名，要设置成你宿主机的IP

**Comment by SpectatorNan** [comment]
是的，我设置的是宿主机的内网IP地址

**Comment by foxiswho** [comment]
使用的 默认配置，什么也没有更改。都是正常的
```shell
Creating network "rmq" with driver "bridge"
Creating rmqnamesrv ... done
Creating rmqbroker  ... done
Creating rmqconsole ... done
bdf02dba15d1        foxiswho/rocketmq:4.7.0         "sh mqbroker -c /etc…"   2 seconds ago       Up Less than a second   0.0.0.0:10909->10909/tcp, 9876/tcp, 10912/tcp, 0.0.0.0:10911->10911/tcp   rmqbroker
53d82d4563c2        styletang/rocketmq-console-ng   "sh -c 'java $JAVA_O…"   2 seconds ago       Up Less than a second   0.0.0.0:8180->8080/tcp                                                    rmqconsole
1742499f83dc        foxiswho/rocketmq:4.7.0         "sh mqnamesrv"           3 seconds ago       Up 2 seconds            10909/tcp, 0.0.0.0:9876->9876/tcp, 10911-10912/tcp                        rmqnamesrv
```

**Comment by foxiswho** [comment]
如果是单机，不是集群，不需要设置 IP

**Comment by foxiswho** [comment]
https://github.com/foxiswho/k8s-nacos-sentinel-rocketmq-zipkin-elasticsearch-redis-mysql

这是 设置 集群的

我这边使用的都是没有问题，现在都是正常运行。 服务器用的 linux. 

本机(MAC)  docker-rocketmq 下的 rmq  启动也正常。

**Comment by haohao1121** [comment]
博主: Mac在虚拟机里启动成功,localhost:8180也可以访问,但是mac主机浏览器无法访问,什么问题

**Comment by foxiswho** [comment]
看你的虚拟机网络方式，要访问虚拟机的IP，才能正常访问

**Comment by remember-5** [comment]
mac 虚拟机中docker安装：
brokerIP1 设置为虚拟机的ip的时候，Java 可以连接，但是web无法链接
brokerIP1未设定，web可以链接，Java无法链接
请问应该如何排查呢？

**Comment by haoxiaoyong1014** [comment]
8024c3e4d8fb        foxiswho/rocketmq:4.7.0         "sh mqbroker -c /e..."   7 seconds ago       Exited (137) 1 second ago

**Comment by haoxiaoyong1014** [comment]
> 8024c3e4d8fb        foxiswho/rocketmq:4.7.0         "sh mqbroker -c /e..."   7 seconds ago       Exited (137) 1 second ago 

mqbroker起不来，没有日志可以看，找不出什么原因

**Comment by haoxiaoyong1014** [comment]
`8024c3e4d8fb foxiswho/rocketmq:4.7.0 "sh mqbroker -c /e..." 7 seconds ago Exited (137) 1 second ago`
mqbroker起不来，没有日志可以看，找不出什么原因

**Comment by haoxiaoyong1014** [comment]
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                       PORTS 
8024c3e4d8fb foxiswho/rocketmq:4.7.0 "sh mqbroker -c /e..." 7 seconds ago Exited (137) 1 second ago
```
mqbroker起不来，没有日志可以看，找不出什么原因?console和mqnamesrv是可以起来的；

**Comment by cikichen** [comment]
m1通过docker desktop安装的镜像，程序能正常连接到namesrv，但是发送消息后会报错连不上broker

**Comment by jwrookie** [comment]
> m1通过docker desktop安装的镜像，程序能正常连接到namesrv，但是发送消息后会报错连不上broker

这是 Docker-For-Mac 的问题，用这个关键词去搜
