### ISSUE TITLE
请问下如何能把消息目录挂载到本地磁盘上，按照传统挂载方式都启动不了，现在一重启docker数据就没了

### ISSUE THREAD

**Issue by LishaoyuVincent** [foxiswho/docker-rocketmq#16]
broker.conf 如下
# 存储路径
storePathRootDir=/opt/rkmq/store
# commitLog 存储路径
storePathCommitLog=/opt/rkmq/commitlog
# 消费队列存储
storePathConsumeQueue=/opt/rkmq/consumequeue
# 消息索引存储路径
storePathIndex=/opt/rkmq/index
# checkpoint 文件存储路径
storeCheckpoint=/opt/rkmq/checkpoint
# abort 文件存储路径
abortFile=/opt/rkmq/abort

dockercompose 如果加上下面的内容挂载到本地磁盘上就启动不来 报rmqbroker exited with code 253
      - ./data/rkmq/store:/opt/rkmq/store
      # # commitLog 存储路径
      - ./data/rkmq/commitLog:/opt/rkmq/commitlog
      # # 消费队列存储
      - ./data/rkmq/consumequeue:/opt/rkmq/consumequeue
      # # 消息索引存储路径
      - ./data/rkmq/index:/opt/rkmq/index
      # # checkpoint 文件存储路径
      - ./data/rkmq/checkpoint:/opt/rkmq/checkpoint
      # # abort 文件存储路径
      - ./data/rkmq/abort:/opt/rkmq/abort

**Comment by foxiswho** [comment]
估计是使用的方式不对。
我这边都是正常的，在服务器上使用都是正常的。本地也是正常的。你是怎么使用的。
启动的时候，你是使用什么命令启动的。`./start.sh` 还是  `docker-compose up`
