### ISSUE TITLE
ACL配置文件改哪个

### ISSUE THREAD

**Issue by eeokee** [foxiswho/docker-rocketmq#17]
版本4.5.2

ACL配置文件改哪个，nameser和broker都有plain_acl.yml。请问改哪个或者映射到哪个路径？

**Comment by foxiswho** [comment]
这里没有使用到ACL ，去官方 http://rocketmq.apache.org/   查看或者咨询

**Comment by eeokee** [comment]
@foxiswho 好的，谢谢
