### ISSUE TITLE
rmq镜像里的runBroker.sh可能有误

### ISSUE THREAD

**Issue by rimwoorim** [foxiswho/docker-rocketmq#20]
# Dynamically calculate parameters, for reference.
Xms=**$MAX_HEAP_SIZE ($MIN_HEAP_SIZE?)** 
Xmx=$MAX_HEAP_SIZE
Xmn=$HEAP_NEWSIZE
MaxDirectMemorySize=$MAX_HEAP_SIZE

**Comment by foxiswho** [comment]
镜像里的都是复制官方的，没有经过任何改动。
