### ISSUE TITLE
java代码中name-server写多少

### ISSUE THREAD

**Issue by chensonghiter** [foxiswho/docker-rocketmq#21]
在centos7上按照楼主的默认配置启动了mq，
在java代码中name-server写成宿主机IP:9876,
测试无法连通mq，报错如下：
org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to <172.20.0.3:10911> failed
Send [3] times, still failed, cost [6011]ms, Topic: test_topic, BrokersSent: [broker-a, broker-a, broker-a]\nSee http://rocketmq.apache.org/docs/faq/ for further details.; nested exception is org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [6011]ms, Topic: test_topic, BrokersSent: [broker-a, broker-a, broker-a]\nSee http://rocketmq.apache.org/docs/faq/ for further details.
控制台http://宿主机IP:8180/#/producer,可正常使用

将broker.conf中的 #brokerIP1=192.168.0.253  这个地方IP改为宿主机IP后，
java代码可正常使用MQ
但是控制台http://宿主机IP:8180/#/producer，会报错连接失败

**Comment by dwh635584069** [comment]
请问楼主解觉了吗，我也出现了这个问题..

**Comment by foxiswho** [comment]
配置文件中更改name-server地址，那么其他地方也要跟着更改
