### ISSUE TITLE
部署时，能不能不用777初始化目录？

### ISSUE THREAD

**Issue by zealinux** [foxiswho/docker-rocketmq#28]
```
# start.sh文件中：

# 设置目录权限
chmod -R 777 ./rmqs/logs
chmod -R 777 ./rmqs/store
chmod -R 777 ./rmq/logs
chmod -R 777 ./rmq/store
```

能不能用更小的权限来初始化目录？

用了777，平台的运维同事直接驳回了。
有安全风险，主机上任何用户都可以改写目录。

**Comment by foxiswho** [comment]
你可以使用nfs 与pvc挂载，让运维同学去学习。  k8s pvc

**Comment by zealinux** [comment]
@foxiswho 我使用docker-compose启动的服务，但是发现权限用666，也是不行的。
然后搜索了一下，`uid="$(id -u)" gid="$(id -g)" docker-compose up -d`这种方式也不行。

有没有其他方式，比如需要在主机上创建个rocketmq的用户？

**Comment by foxiswho** [comment]
宿主机, docker 默认是 root 账户,所以这里也是root账户

**Comment by nary24** [comment]
容器中的rocketmq启动用户为rocketmq,经过查询它的id为 3000
所以把挂载出来的权限设置为以下 
chown 3000:3000  ./rmqs/logs
chown 3000:3000 ./rmqs/store
chown 3000:3000 ./rmq/logs
chown 3000:3000 ./rmq/store
