### ISSUE TITLE
4.8版本和4.7版本配置内存无效

### ISSUE THREAD

**Issue by nary24** [foxiswho/docker-rocketmq#35]
你好，在4.8版本和4.7版本配置内存无效，
如：在docker-compose中配置了JAVA_OPT_EXT=-Xms128m -Xmx128m -Xmn128m参数后，容器启动时未使用我刚指定的配置，希望能在dockerfile中加一下ENV环境变量
配置：
![image](https://user-images.githubusercontent.com/15990601/149058418-5c308ce5-e43a-4abf-ba51-72efc1578161.png)
容器中的内存：
![image](https://user-images.githubusercontent.com/15990601/149058519-2f5c33d7-9b5e-40ff-99ad-bb86f6871bf9.png)

**Comment by foxiswho** [comment]
你看具体的日志,在 这行最后 是你设置的 内存.  你截图的这部分是系统 根据已有内存自动分配的.    自己定义的参数在最后

**Comment by nary24** [comment]
> 你看具体的日志,在 这行最后 是你设置的 内存. 你截图的这部分是系统 根据已有内存自动分配的. 自己定义的参数在最后

好的，谢谢
