### ISSUE TITLE
docker-compose是有问题的建议自己查查，然后测试通过再放出来

### ISSUE THREAD

**Issue by MicroCountry** [foxiswho/docker-rocketmq#4]
1.rmqbroker的environment格式问题，空两格

2.rmqbroker 缺少
links:
   - rmqnamesrv:namesrv

3.NAMESRV_ADDR: "namesrv:9876"
4.command需要去掉，否则有问题

**Comment by zhlid** [comment]
@MicroCountry 第2点 已经有了depend_on   就可以不用 links了吧

**Comment by foxiswho** [comment]
首先谢谢你。
从我这边看了，也测试了，没有任何问题。
你用什么编辑器查看的，看的哪个连接或者版本。 我这边是在  mac  vscode 中查看的，没有你说的那个问题

**Comment by alexchanchan** [comment]
我也发现问题了，首先是JAVA_OPT而不是JAVA_OPTS，第二个rmqbroker的command应该删除，否则需要加JAVA_OPT: "-Duser.home=/opt"，但由于第一个问题的原因，所以在opt的store是空的，日志也找不到broker的日志

**Comment by foxiswho** [comment]
谢谢，已改正
