### ISSUE TITLE
请问如何清除rocketmq中的队列，映射出来的store目录下面是空的?

### ISSUE THREAD

**Issue by zhlid** [foxiswho/docker-rocketmq#5]
启动后进入容器查看 /opt/store目录下也是空的

**Comment by foxiswho** [comment]
根据如下案例 清空，自己更改一下

来源 https://blog.csdn.net/jenny8080/article/details/53467536

1. 停止rocketmq 

可以使用kill -9 命令强制停止rocketmq进程

2. 删除rocketmq日志

rm -rf /root/logs/rocketmqlogs/*

3. 删除rocketmq中topic等信息

rm -rf /root/store/*

4. [可选] 手工清空MQ里剩余的topic，示例命令如下：

cd alibaba-rocketmq/bin

sh mqadmin topicList -n 192.168.1.167:9876

sh mqadmin deleteTopic -c HOSTNAME -n 192.168.1.167:9876 -t orderTopic

5. 重新启动rocketmq，示例命令如下：

cd alibaba-rocketmq/bin

nohup sh mqnamesrv -n 192.168.1.167:9876 > /dev/null 2>&1 &

nohup sh mqbroker -n 192.168.1.167:9876 > /dev/null 2>&1 &

 

PS:

1. 顺序必须是先停止rocketmq,再清空数据；如果顺序错误，可能会导致消息无法正常清除、rocketmq无法启动等问题

2. 删除Topic不是必须的，但是删除的时候需要指定 -c，可以用服务器的hostname试试
